  <?php

	return [
		'entered'			=>['entered'            ,'entered'         ,'get'   ,'group.read'                    ],
		'enteredAll'		=>['enterd/{skp}/{tk}'  ,'allEntered'      ,'get'   ,'group.read'                    ],
		'suggested'			=>['suggested'          ,'suggested'       ,'get'   ,'group.read'                    ],
		'suggestedAll'		=>['sggstd/{skp}/{tk}'  ,'allSuggested'    ,'get'   ,'group.read'                    ],
		'readPost'			=>['read-post'          ,'postRead'        ,'get'   ,'virual.class.post.read'        ],
		'readComment'		=>['read-comment'       ,'commentRead'     ,'get'   ,'virual.class.comment.read'     ],
		'addComment'		=>['add-comment'        ,'commentAdd'      ,'post'  ,'virual.class.comment.add'      ],
		'editComment'		=>['edit-comment'       ,'commentEdit'     ,'post'  ,'virual.class.comment.edit'     ],
		'deleteComment'		=>['delete-comment'     ,'commentDelete'   ,'post'  ,'virual.class.comment.delete'   ],
		'readFile'			=>['read-file/{id}'     ,'fileRead'        ,'get'   ,'virual.class.files.add'        ],
		'addFile'			=>['add-file'           ,'fileAdd'         ,'post'  ,'virual.class.files.edit'       ],
		'editFile'			=>['edit-file'          ,'fileEdit'        ,'post'  ,'virual.class.files.delete'     ],
		'deleteFile'		=>['delete-file'        ,'fileDelete'      ,'post'  ,'virual.class.homework.read'    ],
		'readHomework'		=>['read-homework'      ,'homeWorkRead'    ,'get'   ,'virual.class.homework.add'     ],
		'addHomework'		=>['add-homework'       ,'homeWorkAdd'     ,'post'  ,'virual.class.homework.edit'    ],
		'editHomework'		=>['edit-homework'      ,'homeWorkEdit'    ,'post'  ,'virual.class.homework.delete'  ],
		'deleteHomework'	=>['delete-homework'    ,'homeWorkDelete'  ,'post'  ,'virual.class.exam.read'        ],
		'readExam'			=>['read-exam'          ,'examRead'        ,'get'   ,'virual.class.exam.add'         ],
		'addExam'			=>['add-exam'           ,'examAdd'         ,'post'  ,'virual.class.exam.edit'        ],
		'editExam'			=>['edit-exam'          ,'examEdit'        ,'post'  ,'virual.class.exam.delete'      ],
		'deleteExam'		=>['delete-exam'        ,'examDelete'      ,'post'  ,'virual.class.information.read' ],
		'addInformation'	=>['add-information'    ,'informationAdd'  ,'post'  ,'virual.class.information.edit' ],
		'readChat'			=>['read-chat'          ,'chatRead'        ,'get'   ,'virual.class.chat.read'        ],
		'addChat'			=>['add-chat'           ,'chatAdd'         ,'post'  ,'virual.class.chat.add'         ],
		'readStudent'		=>['read-student'       ,'studentRead'     ,'get'   ,'virual.class.student.read'     ],
		'addStudent'		=>['add-student'        ,'studentAdd'      ,'post'  ,'virual.class.student.add'      ],
		'editStudent'		=>['edit-student'       ,'studentEdit'     ,'post'  ,'virual.class.student.edit'     ],
		'deleteStudent'		=>['delete-student'     ,'studentDelete'   ,'post'  ,'virual.class.student.delete'   ],
		'readMark'			=>['raed-marks'         ,'marksRead'       ,'get'   ,'virual.class.marks.read'       ],
		'addMark'			=>['add-marks'          ,'marksAdd'        ,'post'  ,'virual.class.marks.add'		 ],
		'editMark'			=>['edit-marks'         ,'marksEdit'       ,'post'  ,'virual.class.marks.edit'		 ],
		'deleteMark'		=>['delete-marks'       ,'marksDelete'     ,'post'  ,'virual.class.marks.delete'	 ],
		'readAttendence'	=>['read-attendance'    ,'attendanceRead'  ,'get'   ,'virual.class.attendance.read'	 ],
		'addAttendence'		=>['add-attendance'     ,'attendanceAdd'   ,'post'  ,'virual.class.attendance.add'	 ],
		'editAttendence'	=>['edit-attendance'    ,'attendanceEdit'  ,'post'  ,'virual.class.attendance.edit'	 ],
		'deleteAttendence'	=>['delete-attendance'  ,'attendanceDelete','post'  ,'virual.class.attendance.delete'],
		'readSetting'		=>['read-setting'       ,'settingRead'     ,'get'   ,'virual.class.setting.read'	 ],
		'addSetting'		=>['add-setting'        ,'settingAdd'      ,'post'  ,'virual.class.setting.add'      ],
		'editSetting'		=>['edit-setting'       ,'settingEdit'     ,'post'  ,'virual.class.setting.edit'     ],
		'deleteSetting'		=>['delete-setting'     ,'settingDelete'   ,'post'  ,'virual.class.setting.delete'   ],
	];