<?php

return [
    'me'            => ['me', 'getMe', 'get'],
    'all-me'        => ['all-me/{skp?}/{tk?}', 'getAllMe', 'get'],
    'add-to-group'  => ['add-to-group/{id}/{user}/{param}', 'AddToGroup', 'any'],
    'add-in-gr'     => ['add-in-gr/{id}/{uid}/{allow}', 'AddInGroup', 'get'],
    'addgroup'      => ['addgroup', 'Addgroup', 'post'],
    'editgr'        => ['editgr/{id}', 'postEditgr', 'post'],
    'groupes'       => ['groupes/{id}', 'getGroupes', 'get'],
    'group'         => ['group/{id}', 'Group', 'get'],
    'group-u-count' => ['group-user-count/{id}', 'GroupUserCount', 'get'],
    'entered'       => ['entered', 'entered', 'get'],
    'enteredAll'    => ['all-entered/{skp?}/{tk?}', 'allEntered', 'get'],
    'suggested'     => ['suggested', 'suggested', 'get'],
    'suggestedAll'  => ['all-sggstd/{skp?}/{tk?}', 'allSuggested', 'get'],
    'users'         => ['users/{id}/{skip?}/{take?}', 'Users', 'get'],
    'users-invites' => ['users-invites/{id}/{skp?}/{tk?}', 'UsersInvites', 'get'],
    'users-waiting' => ['users-waiting/{id}/{skp?}/{tk?}', 'UsersWaiting', 'get'],
    'modirator'     => ['modirator/{id}/{skip?}/{take?}', 'Modirator', 'get'],
    'video'         => ['video/{id}/{skip?}/{take?}', 'Video', 'get'],
    'images'        => ['images/{id}/{skip?}/{take?}', 'Images', 'get'],
    'post'          => ['post/{grp?}/{skp?}/{tk?}/{id?}', 'Post', 'get'],
    'postPost'      => ['post/{grp?}', 'postPost', 'post'],
    'postimage'     => ['image', 'postImage', 'post'],
    'search-user'   => ['search-user/{id}/{group}', 'SearchUser', 'get'],
    'editgr'        => ['editgr/{id}', 'postEditgr', 'post'],
    'delete'        => ['delete/{id}', 'delete', 'post'],
    'cover'         => ['cover', 'ChangeCover', 'any'],
    'sugd-user'     => ['suggested-user/{grp}/{skp?}/{tk?}/{sug?}/{sugd?}', 'getSuggestedUser', 'get'],
];
