<?php

return  [
'me'			=>['me'					           ,'me'                            ,'get' ],
'profileUpload'	=>['upload-file/{type}'	           ,'profileUpload'                 ,'post'],
'profile'		=>['prfl/{i}/{skp}/{tk}'           ,'profile'                       ,'get' ],
'ProfilePost'	=>['prflpst/{i}/{skp}/{tk}'        ,'ProfilePost'                   ,'get'  ,'social.post.read'],
'upload-file'	=>['upload-file/{type}'            ,'postUploadFile'                ,'post'],
'profile-wall'	=>['wall/{id}'            		   ,'getProfileWall'                ,'get' ],
'profile-cv'	=>['cv/{id}'           			   ,'getProfileCv'                  ,'get' ],
'header'        =>['header/{id}'                   ,'getProfileHeader'              ,'get' ],
'video'         =>['video/{id}/{skip}/{take}'      ,'getVideo'                      ,'get' ],
'images'        =>['images/{id}/{skip}/{take}'     ,'getImages'                     ,'get' ],
'followers'     =>['followers/{id}/{skip}/{take}'  ,'getProfileFollowers'           ,'get' ],
'friends'	    =>['friends/{id}/{skip}/{take}'    ,'getProfileFriends'             ,'get' ],
'classes'       =>['classes/{id}/{skip}/{take}'    ,'getUserClasses'                ,'get' ],
'countries-list'=>['countries-list'                ,'getGetCountriesList'           ,'get' ],
'available-time'=>['update-available-time'         ,'postUpdateAvailableTime'       ,'post'],
'add-free-hours'=>['add-instructor-free-hours'     ,'postAddInstructorFreeHours'    ,'post'],
'get-free-hours'=>['get-instructor-free-hours'     ,'getGetInstructorFreeHours'     ,'get' ],
'del-free-hours'=>['delete-free-hours'             ,'postDeleteFreeHours'           ,'post'],
'all-me'        =>['all-me/{skip}/{take}'          ,'getAllMe'                      ,'get' ],
'entered'       =>['entered'                       ,'getEntered'                    ,'get' ],
'all-entered'   =>['all-entered/{skip}/{take}'     ,'getAllEntered'                 ,'get' ],
'users'         =>['users/{id}/{skip}/{take}'      ,'getUsers'                      ,'get' ],
'users-invites' =>['users-inv/{id}/{skip}/{take}'  ,'getUsersInvites'               ,'get' ],
'users-waiting' =>['users-wait/{id}/{skip}/{take}' ,'getUsersWaiting'               ,'get' ],
'modirator'     =>['modirator/{id}/{skip}/{take}'  ,'getModirator'                  ,'get' ],
'search-user'   =>['search-user/{id}/{group}'      ,'getSearchUser'                 ,'get' ],
];
